version: '3.8'

services:
  frontend:
    build: .
    container_name: homelabarr-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - homelabarr

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: homelabarr-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3001:3001"
    networks:
      - homelabarr
    group_add:
      - "999"  # Add container to the docker group

networks:
  homelabarr:
    name: homelabarr