services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelabarr-frontend
    restart: unless-stopped
    ports:
      - "8087:80"
    networks:
      - homelabarr
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-frontend/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: homelabarr-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CORS_ORIGIN=http://localhost:8087,http://homelabarr-frontend,http://localhost:8088
      - DOCKER_SOCKET=/var/run/docker.sock
      - AUTH_ENABLED=true
      - JWT_SECRET=${JWT_SECRET:-homelabarr-change-this-secret}
      - JWT_EXPIRES_IN=24h
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:3001"
    networks:
      - homelabarr
    group_add:
      - "999"  # Docker group ID
    # Remove privileged mode for better security
    # privileged: true
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-backend:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  homelabarr:
    name: homelabarr
