# HomelabARR Docker Compose Configuration
#
# Docker Socket Access Configuration:
# - DOCKER_GID: Set this to your host system's docker group ID
#   Find it with: getent group docker | cut -d: -f3 (Linux)
#   Or: cat /etc/group | grep docker (Linux)
#   Default: 999 (common on many systems)
# - DOCKER_SOCKET: Path to Docker socket (default: /var/run/docker.sock)
#
# Example usage:
#   DOCKER_GID=$(getent group docker | cut -d: -f3) docker-compose up -d

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homelabarr-frontend
    restart: unless-stopped
    ports:
      - "8087:80"
    networks:
      - homelabarr
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-frontend/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: homelabarr-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=*
      - DOCKER_SOCKET=${DOCKER_SOCKET:-/var/run/docker.sock}
      - AUTH_ENABLED=false
      - JWT_SECRET=${JWT_SECRET:-homelabarr-change-this-secret}
      - JWT_EXPIRES_IN=24h
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin}
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}:rw
    ports:
      - "8088:3001"
    networks:
      - homelabarr
    group_add:
      - "${DOCKER_GID:-999}"  # Docker group ID - must match host system's docker group
    # Privileged mode removed for security - using group_add instead
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://homelabarr-backend:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  homelabarr:
    name: homelabarr
