# HomelabARR Demo Deployment for Linux/Debian
# This version is optimized for Linux environments with proper path mounting
#
# Demo Configuration:
# - Frontend: http://localhost:8084
# - Backend: http://localhost:8092
# - Linux Docker compatibility
# - CLI integration enabled

services:
  frontend:
    image: ghcr.io/smashingtags/homelabarr-frontend:latest
    container_name: homelabarr-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "8084:8080"  # Match backend CORS expectation
    networks:
      - homelabarr-demo
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    depends_on:
      - backend
    
  backend:
    image: homelabarr-backend-fixed:latest
    container_name: homelabarr-backend
    restart: unless-stopped
    environment:
      # Development environment
      - NODE_ENV=development
      - PORT=8092
      - LOG_LEVEL=debug
      
      # CORS configuration for demo (allow external access)
      - CORS_ORIGIN=*
      
      # Docker configuration for Linux
      - DOCKER_SOCKET=/var/run/docker.sock
      - DOCKER_GID=999
      
      # CLI Bridge configuration - Production mode
      - CLI_BRIDGE_PATH=/homelabarr-cli
      - CLI_INTEGRATION_ENABLED=true
      
      # Authentication - Demo credentials
      - AUTH_ENABLED=false  # Simplified for demo
      - JWT_SECRET=demo-secret-key
      - JWT_EXPIRES_IN=24h
      - DEFAULT_ADMIN_PASSWORD=demo
      
      # Network configuration
      - BIND_ADDRESS=0.0.0.0
      - FRONTEND_URL=http://frontend:8080
      - BACKEND_URL=http://backend:8092
      - EXTERNAL_HEALTH_URL=http://127.0.0.1:8092/health
      
    volumes:
      # Docker socket access (Linux)
      - /var/run/docker.sock:/var/run/docker.sock:rw
      
      # CLI Bridge mount - Linux path (standardized from MVP)
      - ./:/homelabarr-cli:ro
      
      # Data persistence
      - homelabarr-demo-data:/app/data
      
    ports:
      - "8092:8092"  # Match frontend expectation
    networks:
      - homelabarr-demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8092/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

networks:
  homelabarr-demo:
    name: homelabarr-demo
    driver: bridge

volumes:
  homelabarr-demo-data:
    name: homelabarr-demo-data
    driver: local