version: '3'
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "80:80"
      - TZ=UTC
    volumes:
      - ./config:/config
      - ${audiobooks_path}:/audiobooks

networks:
  proxy:
    external: true