version: '3'
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    volumes:

networks:
  proxy:
    external: true