version: '3'
services:
  authentik:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik
    restart: unless-stopped
    networks:
      - proxy
    environment:
      AUTHENTIK_ADMIN_EMAIL: ${admin_email}
      AUTHENTIK_ADMIN_PASSWORD: ${admin_password}
      AUTHENTIK_SECRET_KEY: ${admin_password}  # Not recommended for production
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - ./data:/data
      - ./media:/media

networks:
  proxy:
    external: true