version: '3'
services:
  autoscan:
    image: cloudb0x/autoscan:latest
    container_name: autoscan
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - AUTOSCAN_VERBOSITY=0
      - AUTOSCAN_PLEX_URL=${plex_url}
      - AUTOSCAN_PLEX_TOKEN=${plex_token}
    volumes:

networks:
  proxy:
    external: true