version: '3'
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8083:8083"
      - TZ=UTC
    volumes:
      - ./config:/config

networks:
  proxy:
    external: true