version: '3'
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./config:/config
      - ${books_path}:/books
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`library.${domain}`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls.certresolver=letsencrypt"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.http.routers.calibre.middlewares=authentik@docker"

networks:
  proxy:
    external: true