version: '3'
services:
  cloudcmd:
    image: coderaiser/cloudcmd:latest
    container_name: cloudcmd
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    volumes:
      - ${files_path}:/root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloudcmd.rule=Host(`files.${domain}`)"
      - "traefik.http.routers.cloudcmd.entrypoints=websecure"
      - "traefik.http.routers.cloudcmd.tls.certresolver=letsencrypt"
      - "traefik.http.services.cloudcmd.loadbalancer.server.port=8000"
      - "traefik.http.routers.cloudcmd.middlewares=authentik@docker"

networks:
  proxy:
    external: true