version: '3'
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    ports:
      - "4000:80"
    volumes:
      - ./config:/app/public

networks:
  proxy:
    external: true