version: '3'
services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    restart: unless-stopped
    environment:
      - TZ=UTC
      - LOG_LEVEL=info
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_ENDPOINT=unix:///var/run/docker.sock
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: serve

networks:
  proxy:
    external: true