version: '3'
services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

networks:
  proxy:
    external: true