version: '3'
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - DOZZLE_BASE=/
    ports:
      - "8080:8080"
    volumes:

networks:
  proxy:
    external: true