version: '3'
services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    volumes:
      - ${media_path}:/media
      - ./config:/config
    devices:
      - /dev/dri:/dev/dri # Hardware acceleration support (optional)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.emby.rule=Host(`emby.${domain}`)"
      - "traefik.http.routers.emby.entrypoints=websecure"
      - "traefik.http.routers.emby.tls.certresolver=letsencrypt"
      - "traefik.http.services.emby.loadbalancer.server.port=8096"
      - "traefik.http.routers.emby.middlewares=authentik@docker"

networks:
  proxy:
    external: true