version: '3'
services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - ${media_path}:/media
      - ./config:/config

networks:
  proxy:
    external: true