version: '3'
services:
  fenrus:
    image: revenz/fenrus:latest
    container_name: fenrus
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "3000:3000"
    volumes:

networks:
  proxy:
    external: true