version: '3'
services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    networks:
      - proxy
    pid: host
    environment:
      - GLANCES_OPT=-w
    ports:
      - "61208:61208"
    volumes:

networks:
  proxy:
    external: true