version: '3'
services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    networks:
      - proxy
    pid: host
    environment:
      - GLANCES_OPT=-w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances.rule=Host(`monitor.${domain}`)"
      - "traefik.http.routers.glances.entrypoints=websecure"
      - "traefik.http.routers.glances.tls.certresolver=letsencrypt"
      - "traefik.http.services.glances.loadbalancer.server.port=61208"
      - "traefik.http.routers.glances.middlewares=authentik@docker"

networks:
  proxy:
    external: true