version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${admin_password}
      - GF_SERVER_ROOT_URL=https://grafana.${domain}
    ports:
      - "3000:3000"
    volumes:

networks:
  proxy:
    external: true