version: '3'
services:
  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=guacamole-mysql
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=${mysql_password}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guacamole.rule=Host(`remote.${domain}`)"
      - "traefik.http.routers.guacamole.entrypoints=websecure"
      - "traefik.http.routers.guacamole.tls.certresolver=letsencrypt"
      - "traefik.http.services.guacamole.loadbalancer.server.port=8080"
      - "traefik.http.routers.guacamole.middlewares=authentik@docker"

networks:
  proxy:
    external: true