version: '3'
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "80:80"
      - "443:443"
      - TZ=UTC
    volumes:
      - ./config:/config

networks:
  proxy:
    external: true