version: '3'
services:
  immich:
    image: ghcr.io/immich-app/immich-server:latest
    container_name: immich
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - DB_HOSTNAME=postgres
      - DB_USERNAME=immich
      - DB_PASSWORD=${db_password}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    ports:
      - "3001:3001"
    volumes:
      - ./upload:/usr/src/app/upload
      - ./config:/usr/src/app/config

networks:
  proxy:
    external: true