version: '3'
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - AUTO_UPDATE=true
    ports:
      - "9117:9117"
    volumes:
      - ./config:/config
      - ${downloads_path:-./downloads}:/downloads

networks:
  proxy:
    external: true