version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "8096:8096"
      - "8920:8920"
      - "1900:1900/udp"
    volumes:
      - ${media_path}:/media
      - ./config:/config

networks:
  proxy:
    external: true