version: '3'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - "8096:8096"
      - "8920:8920"
      - "1900:1900/udp"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${media_path:-./media}:/media:ro
    networks:
      - proxy

networks:
  proxy:
    external: true