version: '3'
services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - APP_BASE_URL=https://notes.${domain}
      - APP_PORT=22300
      - ADMIN_PASSWORD=${admin_password}
    ports:
      - "22300:22300"
    volumes:

networks:
  proxy:
    external: true