version: '3'
services:
  kometa:
    image: ghcr.io/kometajs/kometa:latest
    container_name: kometa
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:

networks:
  proxy:
    external: true