version: '3'
services:
  kometa:
    image: ghcr.io/kometajs/kometa:latest
    container_name: kometa
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kometa.rule=Host(`manga.${domain}`)"
      - "traefik.http.routers.kometa.entrypoints=websecure"
      - "traefik.http.routers.kometa.tls.certresolver=letsencrypt"
      - "traefik.http.services.kometa.loadbalancer.server.port=3000"
      - "traefik.http.routers.kometa.middlewares=authentik@docker"

networks:
  proxy:
    external: true