version: '3'
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - "8686:8686"
    volumes:
      - ./config:/config
      - ${music_path:-./music}:/music
      - ${downloads_path:-./downloads}:/downloads

networks:
  proxy:
    external: true