version: '3'
services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - DATABASE_URL=postgresql://${db_user}:${db_password}@postgres:5432/linkwarden
      - NEXTAUTH_SECRET=${auth_secret}
      - NEXTAUTH_URL=https://links.${domain}
    ports:
      - "3000:3000"
    volumes:

networks:
  proxy:
    external: true