version: '3'
services:
  mailcow:
    image: mailcow/mailcow-dockerized:latest
    container_name: mailcow
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - MAILCOW_HOSTNAME=mail.${domain}
      - MAILCOW_PASS=${admin_password}
      - TZ=UTC
    ports:
      - "443:443"
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/vmail:/var/vmail

networks:
  proxy:
    external: true