version: '3'
services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix-synapse
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - SYNAPSE_SERVER_NAME=${domain}
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_ADMIN_PASSWORD=${admin_password}
    ports:
      - "8008:8008"
      - "8448:8448"
    volumes:
      - ./data:/data

networks:
  proxy:
    external: true