version: '3'
services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    container_name: mattermost
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - MM_SERVICESETTINGS_SITEURL=https://chat.${domain}
      - MM_ADMIN_PASSWORD=${admin_password}
    ports:
      - "8065:8065"
    volumes:
      - ./config:/mattermost/config
      - ./data:/mattermost/data

networks:
  proxy:
    external: true