version: '3'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NEXTCLOUD_ADMIN_USER=${admin_user}
      - NEXTCLOUD_ADMIN_PASSWORD=${admin_password}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${domain}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${data_path}:/var/www/html

networks:
  proxy:
    external: true