version: '3'
services:
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
      - DN_API_KEY=${api_key}
    ports:
      - "5454:5454"
    volumes:
      - ./config:/config

networks:
  proxy:
    external: true