version: '3'
services:
  nzbget:
    image: linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - NZBGET_USER=nzbget
      - NZBGET_PASS=${control_password}
    ports:
      - "6789:6789"
    volumes:
      - ./config:/config
      - ${downloads_path}:/downloads

networks:
  proxy:
    external: true