version: '3'
services:
  nzbhydra2:
    image: linuxserver/nzbhydra2:latest
    container_name: nzbhydra2
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5076:5076"
      - TZ=UTC
    volumes:
      - ${config_path}:/config
      - ./downloads:/downloads

networks:
  proxy:
    external: true