version: '3'
services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5055:5055"
      - TZ=UTC
    volumes:
      - ./config:/app/config

networks:
  proxy:
    external: true