version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      - PLEX_CLAIM=${claim_token}
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - VERSION=docker
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${media_path:-./media}:/data:ro
    networks:
      - proxy

networks:
  proxy:
    external: true