version: '3'
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PLEX_CLAIM=${claim_token}
      - TZ=UTC
    ports:
      - "32400:32400"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - ${media_path}:/data
      - ./config:/config

networks:
  proxy:
    external: true