version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      - proxy
    environment:
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_USER: ${postgres_user}
    ports:
      - "5432:5432"
    volumes:
      - ${data_path}:/var/lib/postgresql/data

networks:
  proxy:
    external: true