version: '3'
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - "9696:9696"
    volumes:
      - ${config_path}:/config

networks:
  proxy:
    external: true