version: '3'
services:
  requestrr:
    image: darkalfx/requestrr:latest
    container_name: requestrr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "4545:4545"
    volumes:
      - ./config:/root/config

networks:
  proxy:
    external: true