version: '3'
services:
  rocketchat:
    image: rocket.chat:latest
    container_name: rocketchat
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - ROOT_URL=https://chat.${domain}
      - ADMIN_EMAIL=${admin_email}
      - ADMIN_PASS=${admin_password}
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads

networks:
  proxy:
    external: true