version: '3'
services:
  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8181:8181"
      - TZ=UTC
    volumes:
      - ./config:/config
      - ${plex_logs}:/plex_logs

networks:
  proxy:
    external: true