version: '3'
services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
    volumes:
      - ./config:/opt/unbound/etc/unbound

networks:
  proxy:
    external: true