version: '3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - proxy
    volumes:
      - ./data:/app/data

networks:
  proxy:
    external: true