version: '3'
services:
  vnstat:
    image: vergoh/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    volumes:
      - ./data:/var/lib/vnstat
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vnstat.rule=Host(`bandwidth.${domain}`)"
      - "traefik.http.routers.vnstat.entrypoints=websecure"
      - "traefik.http.routers.vnstat.tls.certresolver=letsencrypt"
      - "traefik.http.services.vnstat.loadbalancer.server.port=80"
      - "traefik.http.routers.vnstat.middlewares=authentik@docker"

networks:
  proxy:
    external: true