version: '3'
services:
  vnstat:
    image: vergoh/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=UTC
    ports:
      - "80:80"
    volumes:
      - ./data:/var/lib/vnstat

networks:
  proxy:
    external: true