version: '3'
services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - ADMIN_EMAIL=${admin_email}
      - PASSWORD=${admin_password}
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yacht.rule=Host(`yacht.${domain}`)"
      - "traefik.http.routers.yacht.entrypoints=websecure"
      - "traefik.http.routers.yacht.tls.certresolver=letsencrypt"
      - "traefik.http.services.yacht.loadbalancer.server.port=8000"
      - "traefik.http.routers.yacht.middlewares=authentik@docker"

networks:
  proxy:
    external: true