version: '3'
services:
  yacht:
    image: selfhostedpro/yacht:latest
    container_name: yacht
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - ADMIN_EMAIL=${admin_email}
      - PASSWORD=${admin_password}
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true